console.log('Data.js loading...');
window.initialStandards = [
    {
        "id": "std-1770091032381",
        "name": "Telcordia SR-332",
        "description": "Reliability Prediction Procedure for Electronic Equipment",
        "version": "issue 3",
        "cost": "",
        "effectiveDate": "2016-03-01",
        "expiryDate": "",
        "category": "MTBF",
        "revisionSummary": "",
        "sourceUrl": "https://telecom-info.njdepot.ericsson.net/site-cgi/ido/docs.cgi?ID=13515794250D000616&KEYWORDS=Reliability%20Prediction%20Procedures%20&TITLE=&DOCUMENT=&DATE=&CLASS=PS71&COUNT=1000"
    },
    {
        "id": "std-1768206238554",
        "name": "IEC 60721-3-3",
        "description": "Classification of environmental conditions - Part 3-3: Classification of groups of environmental parameters and their severities - Stationary use at weatherprotected locations",
        "version": "3.0",
        "cost": "CHF 80.-",
        "effectiveDate": "2019-05-22",
        "expiryDate": "2027 (Stability)",
        "category": "MOXA Standard",
        "revisionSummary": "[2026/1/13更新] 穩定性: 2027",
        "sourceUrl": "https://webstore.iec.ch/en/publication/32620"
    },
    {
        "id": "std-1768268975228",
        "name": "IEC 60721-3-4",
        "description": "Classification of environmental conditions - Part 3-4: Classification of groups of environmental parameters and their severities - Stationary use at non-weatherprotected locations",
        "version": "3.0",
        "cost": "CHF 80.-",
        "effectiveDate": "2019-05-22",
        "expiryDate": "2029 (Stability)",
        "category": "MOXA Standard",
        "revisionSummary": "[2026/1/21更新]版本:  → 3.0",
        "sourceUrl": "https://webstore.iec.ch/en/publication/61080"
    },
    {
        "id": "std-1768459867462",
        "name": "IEC 60721-3-5",
        "description": "",
        "version": "3.0",
        "cost": "CHF 115.-",
        "effectiveDate": "2026-01-14",
        "expiryDate": "2031(Stability)",
        "category": "MOXA Standard",
        "revisionSummary": "[2026/1/21更新]版本:  → 3.0; 價格: - → CHF 115.-",
        "sourceUrl": "https://webstore.iec.ch/en/publication/86315"
    },
    {
        "id": "std-2",
        "name": "IEC 60068-2-1",
        "description": "Environmental testing - Part 2-1: Tests - Test A: Cold",
        "version": "Ed. 7.0 (2025)",
        "effectiveDate": "2025-09-23",
        "expiryDate": "2031 (Stability)",
        "cost": "CHF 210",
        "category": "MOXA Standard",
        "revisionSummary": "技術修訂。更新範圍，新增圖表/符號，闡明風速/測量點程序，重新引入列線圖，修訂溫度公差。",
        "sourceUrl": "https://webstore.iec.ch/en/publication/82354",
        "lastVerified": "2024-11-27",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "temperature-low"
    },
    {
        "id": "std-3",
        "name": "IEC 60068-2-2",
        "description": "Environmental testing - Part 2-2: Tests - Test B: Dry heat",
        "version": "Ed. 6.0 (2025)",
        "effectiveDate": "2025-09-23",
        "expiryDate": "2031 (Stability)",
        "cost": "CHF 260",
        "category": "MOXA Standard",
        "revisionSummary": "技術修訂。更新範圍，新增圖表/符號，闘明風速/測量點程序，重新引入列線圖，修訂溫度公差。",
        "sourceUrl": "https://webstore.iec.ch/en/publication/82355",
        "lastVerified": "2024-11-27",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "temperature-high"
    },
    {
        "id": "std-4",
        "name": "IEC 60068-2-6",
        "description": "Environmental testing - Part 2-6: Tests - Test Fc: Vibration (sinusoidal)",
        "version": "Ed. 7.0 (2007)",
        "effectiveDate": "2007-12-13",
        "expiryDate": "2029 (Stability)",
        "cost": "CHF 295",
        "category": "MOXA Standard",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/544",
        "lastVerified": "2024-12-30",
        "verifiedBy": "Crawler - IEC Webstore",
        "stressType": "vibration"
    },
    {
        "id": "std-5",
        "name": "IEC 60068-2-13",
        "description": "Environmental testing - Part 2-13: Tests - Test M: Low air pressure",
        "version": "Ed. 5.0 (2021)",
        "effectiveDate": "2021-03-03",
        "expiryDate": "2028 (Stability)",
        "cost": "CHF 40",
        "category": "MOXA Standard",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/64534",
        "lastVerified": "2024-12-30",
        "verifiedBy": "Crawler - IEC Webstore",
        "stressType": "pressure"
    },
    {
        "id": "std-6",
        "name": "IEC 60068-2-14",
        "description": "Environmental testing - Part 2-14: Tests - Test N: Change of temperature",
        "version": "Ed. 7.0 (2023)",
        "effectiveDate": "2023-07-27",
        "expiryDate": "2027 (Stability)",
        "cost": "CHF 260",
        "category": "MOXA Standard",
        "revisionSummary": "技術修訂。第7版取消並替換了2009年發布的第6版。包含重大技術變更，分析環境溫度變化對試品的影響。",
        "sourceUrl": "https://webstore.iec.ch/en/publication/71503",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "temperature-cyclic"
    },
    {
        "id": "std-7",
        "name": "IEC 60068-2-30",
        "description": "Environmental testing - Part 2-30: Tests - Test Db: Damp heat, cyclic",
        "version": "Ed. 4.0 (2025)",
        "effectiveDate": "2025-08-07",
        "expiryDate": "2031 (Stability)",
        "cost": "CHF 160",
        "category": "MOXA Standard",
        "revisionSummary": "技術修訂。修訂試驗箱要求，溫度公差，圖表，溫濕度限制，中間測量和試驗報告要求。",
        "sourceUrl": "https://webstore.iec.ch/en/publication/82356",
        "lastVerified": "2024-12-30",
        "verifiedBy": "Crawler - IEC Webstore",
        "stressType": "humidity"
    },
    {
        "id": "std-8",
        "name": "IEC 60068-2-52",
        "description": "Environmental testing - Part 2-52: Tests - Test Kb: Salt mist, cyclic",
        "version": "Ed. 3.0 (2017) RLV",
        "effectiveDate": "2017-11-07",
        "expiryDate": "2027 (Stability)",
        "cost": "CHF 136",
        "category": "MOXA Standard",
        "revisionSummary": "RLV 版本（Redline Version），包含基礎標準",
        "sourceUrl": "https://webstore.iec.ch/en/publication/61926",
        "lastVerified": "2024-12-30",
        "verifiedBy": "Crawler - IEC Webstore",
        "stressType": "salt-mist"
    },
    {
        "id": "std-9",
        "name": "IEC 60068-2-64",
        "description": "Environmental testing - Part 2-64: Tests - Test Fh: Vibration, broadband random",
        "version": "Ed. 2.1 (2019)",
        "effectiveDate": "2019-10-09",
        "expiryDate": "2026 (Stability)",
        "cost": "CHF 515",
        "category": "MOXA Standard",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/65892",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "vibration"
    },
    {
        "id": "std-10",
        "name": "IEC 60068-2-78",
        "description": "Environmental testing - Part 2-78: Tests - Test Cab: Damp heat, steady state",
        "version": "Ed. 3.0 (2025) RLV",
        "effectiveDate": "2025-08-06",
        "expiryDate": "2031 (Stability)",
        "cost": "CHF 136",
        "category": "MOXA Standard",
        "revisionSummary": "RLV 版本。技術修訂，修訂試驗箱要求，嚴酷等級，溫度公差，預處理程序，新圖表和報告要求。",
        "sourceUrl": "https://webstore.iec.ch/en/publication/109062",
        "lastVerified": "2024-12-30",
        "verifiedBy": "Crawler - IEC Webstore",
        "stressType": "humidity"
    },
    {
        "id": "std-11",
        "name": "IEC 60529",
        "description": "Degrees of protection provided by enclosures (IP Code)",
        "version": "2.0",
        "effectiveDate": "1989-11-30",
        "expiryDate": "2027 (Stability)",
        "cost": "CHF 260",
        "category": "MOXA Standard",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/2447",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "ip-protection"
    },
    {
        "id": "std-12",
        "name": "ISTA",
        "description": "International Safe Transit Association Standards",
        "version": "Check Online",
        "effectiveDate": "",
        "expiryDate": "",
        "cost": "",
        "category": "MOXA Standard",
        "revisionSummary": "",
        "sourceUrl": "https://www.ista.org/test_procedures.php",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - ISTA Website",
        "stressType": "packaging"
    },
    {
        "id": "std-13",
        "name": "DNV-CG-0339",
        "description": "Environmental test specification for electrical, electronic and programmable equipment and systems",
        "version": "2021",
        "effectiveDate": "2021-08-01",
        "expiryDate": "",
        "cost": "$57.00",
        "category": "Marine Standard",
        "revisionSummary": "[2026/1/8更新] 價格: Free → $57.00",
        "sourceUrl": "https://store.accuristech.com/standards/dnv-dnv-cg-0339?product_id=2842682",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - DNV Website",
        "stressType": "marine"
    },
    {
        "id": "std-13b",
        "name": "IEC 60945",
        "description": "Maritime navigation and radiocommunication equipment and systems",
        "version": "Ed. 4.0 (2002)",
        "effectiveDate": "2002-08-14",
        "expiryDate": "2028 (Stability)",
        "cost": "CHF 380",
        "category": "Marine Standard",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/3959",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "marine"
    },
    {
        "id": "std-14",
        "name": "IACS E10",
        "description": "Test Specification for Type Approval",
        "version": "Rev. 10 (2024)",
        "effectiveDate": "2024-08-01",
        "expiryDate": "",
        "cost": "Free",
        "category": "Marine Standard",
        "revisionSummary": "",
        "sourceUrl": "https://iacs.org.uk/resolutions/unified-requirements/ur-e/",
        "lastVerified": "2024-12-11",
        "verifiedBy": "Manual - IACS Website",
        "stressType": "marine"
    },
    {
        "id": "std-15",
        "name": "EN 50155",
        "description": "Railway applications - Rolling stock - Electronic equipment",
        "version": "2021",
        "effectiveDate": "2021-07-31",
        "expiryDate": "",
        "cost": "£488",
        "category": "Railway Standard",
        "revisionSummary": "",
        "sourceUrl": "https://knowledge.bsigroup.com/products/railway-applications-rolling-stock-electronic-equipment-1/standard",
        "lastVerified": "2026-01-09",
        "verifiedBy": "Crawler - BSI Knowledge",
        "stressType": "railway"
    },
    {
        "id": "std-16",
        "name": "IEC 61373",
        "description": "Railway applications - Rolling stock equipment - Shock and vibration tests",
        "version": "Ed. 2.0 (2010)",
        "effectiveDate": "2010-05-31",
        "expiryDate": "2026 (Stability)",
        "cost": "CHF 260",
        "category": "Railway Standard",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/5395",
        "lastVerified": "2024-12-30",
        "verifiedBy": "Crawler - IEC Webstore",
        "stressType": "vibration"
    },
    {
        "id": "std-17",
        "name": "IEC 61850-3",
        "description": "Communication networks and systems for power utility automation",
        "version": "Ed. 2.0 (2013)",
        "effectiveDate": "2013-12-12",
        "expiryDate": "2026 (Stability)",
        "cost": "CHF 380",
        "category": "Power Station",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/6010",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "emc"
    },
    {
        "id": "std-18a",
        "name": "IEC 60255-21-1",
        "description": "Electrical relays - Part 21: Vibration, shock, bump and seismic tests - Section 1: Vibration tests (sinusoidal)",
        "version": "Ed. 1.0 (1988)",
        "effectiveDate": "1988-09-30",
        "expiryDate": "2026 (Stability)",
        "cost": "CHF 40",
        "category": "Power Station",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/1167",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "vibration"
    },
    {
        "id": "std-18b",
        "name": "IEC 60255-21-2",
        "description": "Electrical relays - Part 21: Vibration, shock, bump and seismic tests - Section 2: Shock and bump tests",
        "version": "Ed. 1.0 (1988)",
        "effectiveDate": "1988-10-31",
        "expiryDate": "2026 (Stability)",
        "cost": "CHF 80",
        "category": "Power Station",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/1168",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "shock"
    },
    {
        "id": "std-18c",
        "name": "IEC 60255-21-3",
        "description": "Electrical relays - Part 21: Vibration, shock, bump and seismic tests - Section 3: Seismic tests",
        "version": "Ed. 1.0 (1993)",
        "effectiveDate": "1993-09-21",
        "expiryDate": "2026 (Stability)",
        "cost": "CHF 80",
        "category": "Power Station",
        "revisionSummary": "",
        "sourceUrl": "https://webstore.iec.ch/en/publication/1169",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEC Webstore",
        "stressType": "vibration"
    },
    {
        "id": "std-19",
        "name": "IEEE 1613",
        "description": "Environmental and Testing Requirements for Communications Networking Devices in Electric Power Substations",
        "version": "2023",
        "effectiveDate": "2024-02-26",
        "expiryDate": "",
        "cost": "",
        "category": "Power Station",
        "revisionSummary": "",
        "sourceUrl": "https://standards.ieee.org/ieee/1613/10454/",
        "lastVerified": "2024-11-24",
        "verifiedBy": "Manual - IEEE Standards",
        "stressType": "emc"
    }
];
